; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = partitions_1M.csv
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = 
	adafruit/Adafruit GFX Library@^1.12.6
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.2
	adafruit/Adafruit NeoPixel@^1.15.1
